// <auto-generated />
namespace Companyy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class klkl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(klkl));
        
        string IMigrationMetadata.Id
        {
            get { return "202003110936055_klkl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
