// <auto-generated />
namespace Companyy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class osos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(osos));
        
        string IMigrationMetadata.Id
        {
            get { return "202003110324490_osos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
